# 基础镜像，用于运行编译好的 Golang 应用程序
FROM alpine:latest as base

# 创建应用程序所需的目录
RUN mkdir -p /app/etc/log

# 设置工作目录为 /app
WORKDIR /app

# 将编译好的 Golang 应用程序复制到容器中并设置执行权限
COPY ServiceCenter /app/ServiceCenter
RUN chmod +x /app/ServiceCenter

# 设置环境变量
ENV PROJECT_ROOT=/app

# 启动 Golang 应用程序并运行 Nginx
CMD ["/bin/sh", "-c", "/app/ServiceCenter"]