[MongoDB]
username = "root"
password = "root"
ipaddr = "192.168.221.135"
port = "27017"

[Etcd]
endpoints = ["192.168.221.135:2379"]

[MetricManageSvc]
ipaddr = "127.0.0.1"
port = "30001"

[ServiceManageSvc]
ipaddr = "127.0.0.1"
port = "30002"

[Redis]
ipaddr = "192.168.221.135"
port = "6379"