[RedisConf]
ipaddr="127.0.0.1"
port="6379"

[MongoConf]
username="root"
password="root"
ipaddr="127.0.0.1"
port="27017"

[MetricManageSvc]
endpoints=["127.0.0.1:2379"] # etcd的endpoint
ipaddr="127.0.0.1"
port="30001"