version: "3.7"

services:
    etcd:
        image: "bitnami/etcd"
        container_name: "etcd"
        # 总是重启
        restart: "always"
        ports:
            - 2379:2379
        environment:
            # 时区设置
            - TZ=Asia/Shanghai
            # 允许无认证访问
            - ALLOW_NONE_AUTHENTICATION=yes
            # etcd 客户端访问URL
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    mongo:
        image: mongo
        restart: always
        environment:
            TZ: Asia/Shanghai
            MONGO_INITDB_ROOT_USERNAME: root # 替换为你想要的用户名
            MONGO_INITDB_ROOT_PASSWORD: root # 替换为你想要的密码
        ports:
            - 27017:27017 # 将容器的27017端口映射到主机的27017端口

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"

